# Shared
brew "stow"
brew "gum"
brew "zsh"
brew "zsh-autosuggestions"
brew "ripgrep"
brew "pngpaste"
brew "fd"
brew "fzf"
brew "bat"
brew "eza"
brew "zoxide"
brew "starship"
brew "gh"
brew "jq"
brew "btop"
brew "uv"
brew "node"
brew "go"
brew "golangci-lint"
brew "lazydocker"
brew "tealdeer"
brew "tmux"
brew "sesh"
brew "gitmux"
brew "neovim"
brew "tree-sitter"
brew "lazygit"

if OS.linux?
  brew "keychain"
  brew "docker"
  brew "docker-compose"
  brew "docker-buildx"
end

if OS.mac?
  brew "dockutil"
  brew "defaultbrowser"

  cask "zed"
  cask "ghostty"
  cask "helium-browser"
  cask "sourcegit"
  cask "cryptomator"
  cask "obsidian"
  cask "drawio"
  cask "telegram"
  cask "discord"
  cask "docker-desktop"
  cask "calibre"
  cask "iina"
  cask "tor-browser"
  cask "transmission"
  cask "firefox"
  cask "rectangle"

  cask "mactex-no-gui"
  cask "skim"
end
