[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=~/.config/qt6ct/colors/catppuccin-mocha-blue.conf
icon_theme=Papirus-Dark
standard_dialogs=default

[Fonts]
general="Noto Sans,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
fixed="JetBrains Mono,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
underline_shortcut=0
